//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponseData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResponseData()
        {
            this.SessionData = new HashSet<SessionData>();
        }
    
        public int IdResponseData { get; set; }
        public bool CorrectAnswer1 { get; set; }
        public bool CorrectAnswer2 { get; set; }
        public bool CorrectAnswer3 { get; set; }
        public bool CorrectAnswer4 { get; set; }
        public bool CorrectAnswer5 { get; set; }
        public bool CorrectAnswer6 { get; set; }
        public bool CorrectAnswer7 { get; set; }
        public bool CorrectAnswer8 { get; set; }
        public bool CorrectAnswer9 { get; set; }
        public bool CorrectAnswer10 { get; set; }
        public bool CorrectAnswer11 { get; set; }
        public bool CorrectAnswer12 { get; set; }
        public bool CorrectAnswer13 { get; set; }
        public bool CorrectAnswer14 { get; set; }
        public bool CorrectAnswer15 { get; set; }
        public bool CorrectAnswer16 { get; set; }
        public bool CorrectAnswer17 { get; set; }
        public bool CorrectAnswer18 { get; set; }
        public bool CorrectAnswer19 { get; set; }
        public bool CorrectAnswer20 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionData> SessionData { get; set; }
    }
}
