//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SessionData()
        {
            this.StudStat = new HashSet<StudStat>();
        }
    
        public int IdSessionData { get; set; }
        public int Q1ID { get; set; }
        public int Q2ID { get; set; }
        public int Q3ID { get; set; }
        public int Q4ID { get; set; }
        public int Q5ID { get; set; }
        public int Q6ID { get; set; }
        public int Q7ID { get; set; }
        public int Q8ID { get; set; }
        public int Q9ID { get; set; }
        public int Q10ID { get; set; }
        public int Q11ID { get; set; }
        public int Q12ID { get; set; }
        public int Q13ID { get; set; }
        public int Q14ID { get; set; }
        public int Q15ID { get; set; }
        public int Q16ID { get; set; }
        public int Q17ID { get; set; }
        public int Q18ID { get; set; }
        public int Q19ID { get; set; }
        public int Q20ID { get; set; }
        public int IdResponseData { get; set; }
    
        public virtual ResponseData ResponseData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudStat> StudStat { get; set; }
    }
}
