//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudAnswer()
        {
            this.StudStat = new HashSet<StudStat>();
        }
    
        public int IdA { get; set; }
        public string StudAnswer01 { get; set; }
        public string StudAnswer02 { get; set; }
        public string StudAnswer03 { get; set; }
        public string StudAnswer04 { get; set; }
        public string StudAnswer05 { get; set; }
        public string StudAnswer06 { get; set; }
        public string StudAnswer07 { get; set; }
        public string StudAnswer08 { get; set; }
        public string StudAnswer09 { get; set; }
        public string StudAnswer10 { get; set; }
        public string StudAnswer11 { get; set; }
        public string StudAnswer12 { get; set; }
        public string StudAnswer13 { get; set; }
        public string StudAnswer14 { get; set; }
        public string StudAnswer15 { get; set; }
        public string StudAnswer16 { get; set; }
        public string StudAnswer17 { get; set; }
        public string StudAnswer18 { get; set; }
        public string StudAnswer19 { get; set; }
        public string StudAnswer20 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudStat> StudStat { get; set; }
    }
}
