//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudStat
    {
        public int IdSession { get; set; }
        public int IdStud { get; set; }
        public int IdSubject { get; set; }
        public System.DateTime DateTimeSession { get; set; }
        public int IdSessionData { get; set; }
        public int IdA { get; set; }
    
        public virtual SessionData SessionData { get; set; }
        public virtual Stud Stud { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
